# 3.1

In [52]:
import numpy as np

In [53]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
type(ar)

numpy.ndarray

In [55]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [56]:
x = np.array(data)
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
len(c)
len(c[0])

3

In [59]:
#연습문제1
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [60]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
               [[11, 12, 13, 14],
                [15, 16, 17, 18],
                [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [61]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [62]:
a = np.array([1, 2, 3])
print(a.ndim)
print(a.shape)

1
(3,)


In [63]:
c = np.array([[0, 1, 2], [ 3, 4, 5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [64]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


In [65]:
a = np.array([0, 1, 2, 3, 4])
print(a[2])
print(a[-1])


2
4


In [66]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a[0,0])
print(a[-1,-1])

0
5


In [67]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(a)
print(a[0, :])
print(a[:, 1])
print(a[1, 1:])
print(a[:2, :2])

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


In [68]:
#연습문제2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
print(m)
print(m[1, 2])
print(m[2, 1])
print(m[1:,2])
print(m[:2,3:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
11
[ 7 12]
[[3 4]
 [8 9]]


In [69]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
print(a % 2)
a[a % 2 == 0]

[0 1 0 1 0 1 0 1 0 1]


array([0, 2, 4, 6, 8])

In [70]:
#연습문제3
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(x[x % 3 == 0])
print(x[x % 4 == 1])
idx1 = x % 3 == 0
idx2 = x % 4 == 1
idx3 = idx1 & idx2
print(x[idx3])


[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


#3.2

In [71]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [72]:
b = np.zeros((2,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]


In [89]:
a1 = np.zeros((3, 3))

a2 = np.ones((3, 2))

a3 = np.arange(10, 151, 10)

a4 = a3.reshape(3, -1)


x = np.hstack([a1, a2])

y = np.vstack([x, a4])

z = np.vstack([y, y])
print(z)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


#3.3

In [98]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x
y = np.arange(5)[:, np.newaxis]
y
x+y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [104]:
# 연습문제 3.3.1
a = np.array(range(30))
print(a)
aa = a.reshape(5,6)
print(aa)

print(aa.max())
print(aa.sum(axis = 1))
print(aa.max(axis = 1))
print(aa.mean(axis = 0))
print(aa.min(axis = 0))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
29
[ 15  51  87 123 159]
[ 5 11 17 23 29]
[12. 13. 14. 15. 16. 17.]
[0 1 2 3 4 5]


In [109]:
#연습문제 3.3.2
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
idx = np.argsort(a[1])
print(idx)
print(a[:,idx])

[0 3 1 2]
[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


#3.4

In [110]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [111]:
len(x)

26

In [112]:
np.mean(x)

np.float64(4.8076923076923075)

In [113]:
np.var(x)

np.float64(115.23224852071006)

In [114]:
np.var(x, ddof=1)

np.float64(119.84153846153846)

In [115]:
np.std(x)

np.float64(10.734628476137871)

In [116]:
np.max(x)

np.int64(23)

In [117]:
np.min(x)

np.int64(-24)

In [118]:
np.median(x)

np.float64(5.0)

In [119]:
np.percentile(x,0)

np.float64(-24.0)

In [121]:
np.percentile(x,25)

np.float64(0.0)

In [122]:
np.percentile(x,50)

np.float64(5.0)

In [123]:
np.percentile(x, 75)

np.float64(10.0)

In [124]:
np.percentile(x, 100)

np.float64(23.0)

#3.5

In [125]:
np.random.seed(0)

In [126]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [131]:
#연습문제 3.5.1
coin = np.random.choice(2, 10, replace=True)
print(coin)

num = np.array(range(1,7))
print(num)
dice = np.random.choice(num, 100, replace=True)

m = np.mean(dice)
print(m)

[0 1 1 1 1 0 1 0 0 1]
[1 2 3 4 5 6]
3.39


In [136]:
#연습문제 3.5.2
per = np.random.randn(250)
price = 10000
p = []
for i in per:
    price = (i/100 + 1) * price
    p.append(float(price))

print(p)

[10020.659646175123, 10204.124010551594, 10272.738415442594, 10336.733644106556, 10373.410816873691, 10522.047993906324, 10487.711120899317, 10668.898232552687, 10736.278091907734, 10820.422792119125, 10818.996613624697, 10783.572790414888, 10774.999765108087, 10718.4948127527, 10840.29211549057, 10568.829609326669, 10768.892153299319, 10738.67138220426, 10961.591837937318, 11186.355685694776, 11217.304992106358, 11449.079180441584, 11511.248654838793, 11478.015375649076, 11622.553425047812, 11701.445166373827, 11599.918341499098, 11545.047995594861, 11392.861500078487, 11532.485417708964, 11664.181503595608, 11637.580679855275, 11638.969352422431, 11733.24986394488, 11697.303869727939, 11574.419566059278, 11675.969383919859, 11587.8019968165, 11712.28703463311, 11721.840327179034, 11643.872640335856, 11626.850983709375, 11692.362154654851, 11891.995317329338, 11936.543774448632, 11814.129154337392, 11867.240552213736, 11886.081319579016, 11991.339515607366, 11632.80645571854, 11608.55