## 2.12 파이썬 객체지향 프로그래밍

객체 - 서로 연관된 데이터와 그 데이터를 조작하기 위한 함수를 하나의 집합에 모아 놓은 것

객체의 속성인 함수 - 메서드

In [1]:
class Rectangle(object):

    def __init__(self, h, v):
        self.h = h
        self.v = v

    def area(self):
        return self.h * self.v

In [ ]:
r = Rectangle(10, 20)
a = r.area()
print(a)

객체를 만들려면 객체를 바로 만들지 못하고 항상 클래스를 만들어야 함

class 클래스이름(object):
    
    def __init__(self, 속성값1, 속성값2, 속성값3):
        self.속성이름1 = 속성값1
        self.속성이름2 = 속성값2
        self.속성이름3 = 속성값3

    def area(self):
        return self.속성이름1 * self.속성이름2 

In [3]:
class nemogidung(object):
    
    def __init__(self, a, b, h):
        self.a = a
        self.b = b
        self.h = h
    
    def surface(self):
        return 2 * (self.a * self.b + self.b * self.h + self.h * self.a)
    
r = nemogidung(1,2,3)
a = r.surface()
print(a) 

22


## 3.1 넘파이 배열

In [6]:
import numpy as np
ar = np.array([0,1,2,3,4,5,6,7,8,9])
print(ar)
type(ar)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [10]:
# 연습문제 1
c = np.array([[10,20,30,40], [50,60,70,80]])  
c

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [12]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])   # 2 x 3 x 4 array
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

ndim = 배열의 차원
shape = 배열의 크기

배열 슬라이싱 a[행, 열] 전체 슬라이싱을 위해선 : 작성

In [13]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [21]:
# 연습문제 2
print(m[1,2])
print(m[-1,-1])
print(m[1,1:3])
print(m[1:3,2])
print(m[0:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [26]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
p=x%3==0
print(x[p])
p=x%4==1
print(x[p])
p=(x%3==0)&(x%4==1)
print(x[p])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


## 3.2 배열의 생성과 변형

## 넘파이의 자료형

크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 
a = np.zeros(5)
로 하면 됨

b = np.zeros((2, 3))
이걸론 다차원도 가능

np.arange(10)  # 0 .. n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(3, 21, 2)  # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

T는 행-열을 바꾸는 2차원 배열의 전치 연산 가능
reshape로 형태만 변경 가능 (행렬 형태 변경인 듯)

flatten이랑 ravel쓰면 일차원 가능

배열 연결도 가능
hstack은 옆으로 연결
vstack은 밑으로 연결 -> 리스트 형태로 넘겨야함 np.vstack ([a1,a2])
dstack은 깊이로 연결?

In [39]:
b1 = np.zeros((3, 3))
b2 = np.ones((3, 2))
b3 = np.hstack([b1, b2])
b4 = np.arange(10, 151, 10)
b5 = b4.reshape(3,5)
b6 = np.vstack([b3,b5])
np.vstack([b6,b6])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

## 3.3 배열의 연산

In [5]:
import numpy as np

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

z = x + y
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

a >= b

array([False,  True,  True,  True])

In [9]:
np.all(a==b)

False

In [10]:
10*a

array([10, 20, 30, 40])

In [11]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
import numpy as np

# 5x6 형태의 데이터 행렬 생성
a = np.random.rand(5, 6)

# 전체 최댓값
b = np.max(a)

# 각 행의 합
sum = np.sum(a, axis=1)

# 각 행의 최댓값
max = np.max(a, axis=1)

# 각 열의 평균
mean = np.mean(a, axis=0)

# 각 열의 최솟값
min = np.min(a, axis=0)


In [15]:
a = np.array([[1, 2, 3, 4],
                 [46, 99, 100, 71],
                 [81, 59, 90, 100]])

b = np.argsort(a[1])
c = a[:, b]
c

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

## 3.4 기술 통계

In [17]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

len(x)  
np.mean(x)  # 평균
np.var(x)  # 분산
np.std(x) # 표준편차
np.max(x) # 최대
np.min(x) # 최소
np.median(x) # 중앙값

115.23224852071006

In [ ]:
np.percentile(x, 25)  # 1사분위 수
# 0 / 25 / 50 / 75 / 100 (최소/1/2/3분위 수/최대)

## 3.5 난수 발생과 카운팅

In [21]:
np.random.seed(0)
np.random.rand(5)

np.random.seed(0)
np.random.rand(5)

# 다시 해도 같은 수가 나옴

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [22]:
np.random.shuffle(x) # 순서 변경
x

array([ 15, -24,  23,  -1,  10, -13,  -7,  15,   2,  18,  23,  -6,   4,
         0,   2,   5,  -8,   5,   0,   9,   5,   8,  10,  19,   4,   7])

In [26]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.
np.random.choice(5, 3, replace=False)  # 3개만 선택
np.random.choice(5, 10)  # 반복해서 10개 선택
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])  # 선택 확률을 다르게 해서 10개 선택

array([3, 3, 3, 3, 3, 3, 3, 2, 3, 2])

In [28]:
np.random.rand(10) # 난수 생성
np.random.rand(3, 5)
np.random.randn(10) # 난수긴 한데 기댓값이 0이고 표편이 1임 (표준 정규 분포)

array([-0.475776  ,  1.44073112, -1.14907568,  0.80571455,  1.75610703,
        0.97297991, -1.55111911,  0.19114348,  1.60477607, -1.42002593])

numpy.random.randint(low, high=None, size=None)
high를 입력하지 않으면 0과 low사이의 숫자를, high를 입력하면 low와 high는 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [30]:
a = np.random.choice([0, 1], size=10)
print(a)

[1 1 0 1 1 1 1 0 0 1]


In [31]:
a = np.random.choice([1, 2, 3, 4, 5, 6], size=100)
b = np.mean(a)
print(b)

3.65


In [32]:
a = 10000
b = np.random.normal(0, 0.01, 250)
c = a * np.cumprod(1 + b)
print(c)
# 출력: [10059.42994341, 10040.67307111, ...]  (예시)

[ 9993.17583947 10164.39319037 10088.69338196 10005.3165318
  9995.4660451   9929.14829827 10041.01364976  9932.57757959
  9818.60436549  9775.61654747  9726.9308048   9914.61505254
 10008.74647077 10017.50925255  9894.75113607  9978.29875127
  9878.49427575  9725.89415138  9841.44067147  9872.63239059
  9963.5453971   9995.30197149 10080.94477854 10015.31524798
  9911.73256695  9979.29039279  9899.11580936  9830.85647829
  9786.07373166  9787.78425505  9753.13609474  9619.03522386
  9557.12534298  9344.63191685  9403.05749457  9252.41509212
  9150.23296135  9155.00618762  9087.29914954  9227.51750175
  9108.21890413  9132.5424819   9128.95496183  9022.32023251
  9069.53192853  9053.97347925  9123.85119107  9198.98648463
  9397.98226723  9523.58892692  9488.42956628  9465.71624162
  9569.80689859  9632.5143723   9694.17513355  9537.42458278
  9535.10449701  9464.7324786   9491.22659304  9481.91091716
  9568.21327041  9598.56538577  9674.04158936  9628.92001196
  9537.98003742  9498.869