3.1 넘파이 배열
-배열: 모든 원소가 같은 자료형을 가진다. 원소의 개수를 바꿀 수 없다.
    --> ndarray 클래스

# 넘파이 패키지 임포트
import numpy as np

# 1차원 배열 만들기
ar = np.array([0, 1, 2, 3, 4])
이렇게 만들어진 배열은 리스트와 동일한 구조처러 보이지만 원소에 대한 접근이 더 빨라짐

# 벡터화 연산
data = [0, 1, 2, 3, 4, 5]
x = np.array(data)
2*x
실행결과: array([ 0,  4,  6,  8, 10])

참고로 일반적인 리스 객체에서 정수를 곱하면 그 크기가 정수배 만큼 증가한다.
비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용된다.
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
2 * a + b
실행결과: array([12, 24, 36])

# 2차원 배열 만들기
ndarray는 다차원 배열 자료 구조를 지원한다.
다음과 같이 리스트의 리스트를 이용하면 2차원 배열을 생성할 수 있다.
c = np.arry([[0, 1, 2], [3, 4, 5]])
c
실행결과: c는 2행 3열인 행렬이 된다.

len(c)
len(c[0])
실행결과: 전자는 행의 개수를 구할 수 있고 후자는 열의 개수를 구할 수 있다.

In [91]:
#연습문제1
import numpy as np
ar = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
ar

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# 3차원 배열 만들기
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
len(d), len(d[0]), len(d[0][0])
실행결과: 2x3x4 배열인 d 생성
         배열의 깊이, 행, 열

# 배열의 차원과 크기 알아내기
ndim 속성은 배열의 차원을, shape 속성은 배열의 크기를 반환한다.

c = np.array([[0, 1, 2], [3, 4, 5]])
print(c.ndim)
print(c.shape)
실행결과:2
        (2, 3)

# 배열의 인덱싱
일차원 배열의 인덱싱은 리스트의 인덱싱과 같다.
다차원 배열인 경우, 콤마를 사용하여 접근할 수 있다.
a = np.array([[0, 1, 2], [3, 4, 5]])
a[0,1]
실행결과: 1 #첫 번째 행의 두 번째 열

# 배열의 슬라이싱
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a[0, :]  # 첫번째 행 전체
a[:, 1]  # 두번째 열 전체
a[1, 1:]  # 두번째 행의 두번째 열부터 끝열까지

In [92]:
#연습문제2
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
print(m[1, 2])
print(m[2, -1])
print(m[1,1:3])
print(m[1:3, 2])
print(m[0:2, 3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


# 배열 인덱싱 == 팬시 인덱싱
배열 인덱싱은 데이터베이스의 쿼리 기능을 수행한다.
배열 인덱싱으로 대괄호 안의 인덱스로 또 다른 ndarray 배열을 받을 수 있다.
1. 정수 배열 방식
    인덱스 배열의 원소 각각이 원래 ndarray 객체 원소 하나를 가르키는 정수이다.
    배열의 인덱스가 원래의 배열보다 더 커지기도 한다.

2. 불리언 배열 방식
    특정 인덱스를 선택할 지 선택하지 않을 지 True, False로 결정

    a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    idx = np.array([True, False, True, False, True,
               False, True, False, True, False])
    a[idx]
    실행결과: array([0, 2, 4, 6, 8])

In [93]:
#연습문제3
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(x[x%3 == 0])
print(x[x%4 == 1])
print(x[(x%3 == 0) & (x%4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


3.2 배열의 생성과 변형
#넘파이의 자료형
array 명령으로 배열을 만들 때, 자료형을 명시적으로 적용하려면 dtype 인수를 사용한다.
dtype 인수가 없으면 주어진 데이터를 저장할 수 있는 자료형을 스스로 유추한다.

dtype 인수로 지정할 자료형은 다음 표에 보인 것과 같은 "dtype 접두사"로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
x = np.array([1, 2, 3], dtype='f')
x.dtype
실행 결과: dtype('float32')

# Inf와 NaN
np.inf는 무한대를 표현하고 np.nan은 정의할 수 없는 숫자를 나타낸다.

np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
실행결과: array([  0.,  inf, -inf,  nan])

# 배열 생성
넘파이는 몇 가지 단순한 배열을 생성하는 명령을 제공한다.
1. 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 명령을 사용한다
    a = np.zeros(5)
    a
    실행결과: array([0., 0., 0., 0., 0.])
    크기를 뜻하는 튜플을 입력하면 다차원 배열도 만들 수 있다.
    문자열 배열도 가능하지만 모든 원소의 문자열 크기가 같지 않으면 잘릴 수 있다.

2. 0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용한다.
    만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령을 사용한다.
    f = np.ones_like(b, dtype="f")
    f
    실행결과: array([[1., 1., 1.],
                    [1., 1., 1.]], dtype=float32)

3. arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있다.

4. linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.

# 전치 연산
2차원 배열의 전치 연산은 행과 열을 바꾸는 작업이다.
이는 배열의 T속성으로 구할 수 있다. 

A = np.array([[1, 2, 3], [4, 5, 6]])
A
실행결과: array([[1, 2, 3],
       [4, 5, 6]])
A.T
실행결과: array([[1, 4],
       [2, 5],
       [3, 6]])

# 배열의 크기 변형
1. 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용한다.

a = np.arange(12)
b = a.reshape(3, 4)
b
실행결과: array([[ 0,  1,  2,  3],
                [ 4,  5,  6,  7],
                [ 8,  9, 10, 11]])

사용하려는 원소의 개수가 정해져 있기 때문에 튜플의 원소 중 하나는 -1로 대체할 수 있으며 자동으로 알맞은 값이 사용된다.

2. 다차원 배열을 1차원으로 만들기 위해서는 flatten 나 ravel 메서드를 사용한다.
a.flatten()
실행결과: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
a.ravel()
실행결과: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

3. 같은 배열에 대해 차원만 증가시키는 경우에는 newaxis 명령을 사용한다.
x[:, np.newaxis]
실행결과: array([[0],
                [1],
                [2],
                [3],
                [4]])

# 배열 연결
1. hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다. 연결할 배열은 하나의 리스트에 담아야 한다.

a1 = np.ones((2, 3))
a2 = np.zeros((2, 2))
np.hstack([a1, a2])
실행결과: array([[1., 1., 1., 0., 0.],
                [1., 1., 1., 0., 0.]])

2. vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만든다.

3. dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합친다. 
가장 안쪽의 원소의 차원이 증가한다. 즉 가장 내부의 숫자 원소가 배열이 된다. shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것이다.
이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 된다.

c1 = np.ones((3, 4))
c2 = np.zeros((3, 4))
np.dstack([c1, c2])
실행결과:array([[[1., 0.],
                [1., 0.],
                [1., 0.],
                [1., 0.]],

                [[1., 0.],
                [1., 0.],
                [1., 0.],
                [1., 0.]],

                [[1., 0.],
                [1., 0.],
                [1., 0.],
                [1., 0.]]])

4. stack 명령은 사용자가 지정한 차원(축으로) 배열을 연결한다.
다음 예에서는 axis=0 이므로 가장 바깥에 값이 2인 차원이 추가된다. 즉, shape 변화는 2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 이다..
c = np.stack([c1, c2])
실행결과:array([[[1., 1., 1., 1.],
              [1., 1., 1., 1.],
              [1., 1., 1., 1.]],

              [[0., 0., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 0.]]])

5. r_ 메서드는 배열을 좌우로 연결한다. 대괄호를 사용한다.
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]
실행결과: array([1, 2, 3, 4, 5, 6])

6. c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결한다.

7. tile 명령은 동일한 배열을 반복하여 연결한다.

In [94]:
#연습문제 3.2.1
a1 =  np.zeros((3, 3))
a2 = np.ones((3,2))
b3 = np.arange(10, 160, 10)
a3 = b3.reshape(3, 5)
c1 = np.hstack([a1, a2])
c2 = np.vstack([c1, a3])
c3 = np.vstack([c2, c2])
c3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

# 2차원 그리드 포인트 생성
meshgrid 명령은 사각형 영역을 구성하는 가로, 세로 축의 점을 나타내는 2개의 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합을 출력한다. 

x = np.arange(3)
y = np.arange(5)
X, Y = np.meshgrid(x, y)
[list(zip(x, y)) for x, y in zip(X, Y)]

3.3 배열의 연산
#벡터화 연산
사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능하다.
배열의 모든 원소가 다 같은지 알고 싶다면 all 명령을 사용한다.

np.all(a == b)

# 브로드캐스팅
넘파이는 서로 다른 크기를 가진 두 배열의 사칙 연산도 지원한다.
크기가 작은 배열을 자동으로 확장하여 크기가 큰 배열에 맞추는 방법이다.

# 차원 축소 연산
x.min()
x.max()
x.argmin()  # 최솟값의 위치
x.argmax()  # 최댓값의 위치

In [95]:
#3.3.1
a = np.arange(30)
a1 = a.reshape(5, 6)
print(a1.max())
print(a1.sum())
print(a1.max(axis = 1))
print(a1.mean(axis = 0))
print(a1.min(axis = 0))

29
435
[ 5 11 17 23 29]
[12. 13. 14. 15. 16. 17.]
[0 1 2 3 4 5]


# 정렬
1. sort 함수나 메서드를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만들 수도 있다. 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬하는데 axis 인수를 사용하여 행을 정렬할 것인지 열을 정렬한 것인지 결정한다. axis=0이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정렬한다. 디폴트 값은 -1 즉 가장 안쪽(나중)의 차원이다.

2.만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용한다.

In [96]:
#3.3.2
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
b = np.argsort(a[1,:])
b
a[:,b]


array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

3.5 난수 발생과 카운팅
# 시드 설정하기
seed를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다.
1. 시드를 설정하는 함수는 seed이다.
    인수로 0보다 크거나 같은 정수를 넣는다.

2. 난수를 설정하는 함수는 rand이다.
    0과 1사이의 난수를 발생시킨다.

# 데이터의 순서 바꾸기
데이터의 순서를 바꿀 때, shuffle 함수를 사용한다.

# 데이터 샘플링
이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 표본선택 혹은 샘플링(sampling)이라고 한다.
1. 샘플링에는 choice 함수를 사용한다.
numpy.random.choice(a, size=None, replace=True, p=None)
size는 샘플의 숫자, replace는 복원추출, p는 각 데이터가 선택될 확률

# 난수 생성
1. rand 함수는 0부터 1사이에서 균일한 확률로 실수 난수를 생성한다.

2. randn 함수는 기댓값이 0이고 표준편차가 1인 표준 정규분포를 따르는 난수를 생성한다.

3. randint 함수는 다음과 같은 인수를 가진다.
numpy.random.randint(low, high=None, size=None)
high를 입력하지 않으면 0과 low 사이의 숫자를, high를 입력하면 low와 high 사이의 숫자를 출력한다. size는 난수의 숫자이다.

In [97]:
#연습문제 3.5.1
a = np.arange(1, 3)
print(np.random.choice(a, 10, replace = True, p =[0.5, 0.5]))

b = np.arange(1, 7)
print(np.mean(np.random.choice(b, 100, replace = True)))

[1 1 2 1 1 2 2 1 1 1]
3.44


In [98]:
#3.5.2
a = np.random.randn(250)
b = (a+100)/100
price = 10000
c = []
for i in range(250):
    price = price*b[i]
    c.append(price)

ans = np.array(c)
ans

array([ 9959.03242318,  9999.04982314,  9891.0124666 ,  9824.52811226,
        9723.09013315,  9743.00731682,  9672.44958114,  9695.18951446,
        9733.87833728,  9771.35719621,  9710.42229991,  9593.66924623,
        9736.67896749,  9675.25433516,  9592.80221123,  9383.39305003,
        9392.16075977,  9391.1997628 ,  9417.18484952,  9563.07584387,
        9517.66197328,  9597.847735  ,  9657.4734557 ,  9707.60125555,
        9687.16014907,  9666.63354805,  9482.87617673,  9469.42264171,
        9568.18100475,  9586.05732346,  9451.11065832,  9377.03842791,
        9313.79656595,  9248.87169938,  9321.28243752,  9468.83491315,
        9278.33307019,  9428.88180639,  9443.98781919,  9484.69283086,
        9465.94404306,  9531.86081103,  9446.39961834,  9423.39228009,
        9488.52285875,  9450.40140583,  9517.18136337,  9417.89707511,
        9397.33971174,  9237.5544066 ,  9054.56292907,  9072.58544516,
        9273.37866567,  9382.3728023 ,  9340.67974512,  9251.14999852,
      

# 정수 데이터 카운팅
1. unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력한다.
    return_counts 인수를 True로 설정하면 각 값을 가진 데이터의 갯수도 출력한다.

2. 데이터가 특정 범위 안의 수인 경우에는 bicount 함수에 minlength 인수를 사용한다.
    0부터 minlength-1까지의 숫자에 대해 각각 카운트를 한다.